repos:
  - repo: local
    hooks:
      - id: dump-structured-readme-and-validate-links
        name: Dump structured readme and validate links
        entry: python scripts/validate_readme.py
        language: system