name: Validate README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -U pydantic httpx

    - name: Validate README structure
      run: python scripts/validate_readme_structure.py
    
    - name: Validate README links
      if: github.event_name == 'push'
      run: python scripts/validate_readme_links.py
